### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by pathapatisivayya** [hnarayanan/CS231n#1]
y_test_pred = best_svm.predict(X_test_feats)

test_accuracy = np.mean(y_test == y_test_pred)
print test_accuracy

TO RUN CODE SOME ERROR COMING PLEASE HELP ME TEAM 

AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by hnarayanan** [comment]
Hello and sorry. This is just a listing of course material, not a place for support (yet).

I am working on a forum for discussion around this (and other) class material, and I'll share that when ready. You will be able to ask a community for help there.
